services:
  php:
    image: xint0/banxico-php
    build:
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
    volumes:
      - .:/usr/src/app
      - phive:/root/.phive
  phpstan:
    image: xint0/banxico-phpstan
    build:
      dockerfile: docker/phpstan/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.2}
    volumes:
      - .:/app

volumes:
  phive: